name       : attica
version    : 5.48.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/attica-5.48.0.tar.xz : 087fef3a77b5193eca081730f9bed181e1ffbd36a5a09352e3233a58df1841e0
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
