name       : attica
version    : 5.45.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/attica-5.45.0.tar.xz : c506843f635943dad70600ec0c6dda85bb23a19a1bc0aeb5110f362aa454ebef
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
