name       : attica
version    : 5.43.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/attica-5.43.0.tar.xz : 2ac4197eb97fd09bafbfe91bb90b9cf0cc8e65f2cdc20cd54ba63adb402b6eef
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
