name       : attica
version    : 5.80.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/attica-5.80.0.tar.xz : e3aa866b01dfcdc1f59012c57f6bd49eabfe5d920560f766116a6633b394ce71
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-only
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
