name       : attica
version    : 5.58.0
release    : 26
source     :
    - https://download.kde.org/stable/frameworks/5.58/attica-5.58.0.tar.xz : edba3f94705f904edb0bddd5bab491575bb15ee8f278b92b41272d6f566cad2a
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
