name       : attica
version    : 5.69.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/attica-5.69.0.tar.xz : 2f96730c4299987524b282dd7638d0ecb0c88ec0e6e8c47f6080d49de7619d3b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
