name       : attica
version    : 5.84.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/attica-5.84.0.tar.xz : adb8afbbe73d89e07dee77a4ee0d9553b4611ee5e69effe9e0d9881b54abb1e0
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-only
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
