name       : attica
version    : 5.78.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/attica-5.78.0.tar.xz : 15f194688ffaa78b5cc093c61c08f7002f7eff042ce202466c67077f13d49676
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-only
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
