name       : attica
version    : 5.44.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/attica-5.44.0.tar.xz : 4376a1910477b3e0e2b6dae904ce53576a2d4d0bab616413d3a5b5c2f29882a9
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
