name       : attica
version    : 5.32.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.32/attica-5.32.0.tar.xz : e5428cda35021d00baecb16cadf12a08c84ef15e61e72790ae6e33ccef1b749b
license    : LGPL-2.1
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
