name       : attica
version    : 5.47.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/attica-5.47.0.tar.xz : 72a1962de852590d9494ebcfa9f98e1d394bad4680384b9a6937a7082140259e
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
