name       : attica
version    : 5.41.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/attica-5.41.0.tar.xz : 077b6cac59ebfb2d6e529653cae21f5ced26d54ff79c86687ee78f021cc427d1
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
