name       : attica
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/attica-5.25.0.tar.xz : 951af772a83237d2c0c9a7fede2608101041d2cc13716221c97d9c79cc79e5be
license    : LGPL-2.1
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
