name       : attica
version    : 5.68.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/attica-5.68.0.tar.xz : 9b4001a32831c9bae1d44161247acd5e6d3048ca2ece98c2c756c72a1464b9e9
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
