name       : attica
version    : 5.39.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.39/attica-5.39.0.tar.xz : 4ec1527e54e029c88135b5ed4851874ebb19a566b3c690c62ce6118b42112795
license    : LGPL-2.1
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
