name       : attica
version    : 5.40.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/attica-5.40.0.tar.xz : 3f1a907031a93cf505920482092ba5c362be639ccc9fb539f0365049a137e7d9
license    : LGPL-2.1
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
