name       : attica
version    : 5.42.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/attica-5.42.0.tar.xz : adfba910d6d3bbd814b8b8e7322e8181696f180f6088b53cb726e6a5cbd49245
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
