name       : attica
version    : 5.36.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.36/attica-5.36.0.tar.xz : 8dd2998f5c9b5f727ec406385f065907f1c6b094ac47d3c1eaae2b858c9f258a
license    : LGPL-2.1
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
