name       : attica
version    : 5.85.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/attica-5.85.0.tar.xz : 345fb419e5ef64dc23e3cfda3a8d9877fa915cd0b5d8dee0517d4326be148be7
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-only
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %patch -p1 < $pkgfiles/fix-parallel-fetch.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
